---
- name: Claude role tasks
  tags: claude
  block:
    - name: Set fact
      ansible.builtin.import_tasks: 10-set-fact.yaml
    - name: Setup claude
      ansible.builtin.import_tasks: 11-setup-claude.yaml
