---
- name: includes | set_brew_prefix | Check Homebrew/Linuxbrew
  ansible.builtin.command: which brew
  changed_when: false
  check_mode: false

- name: includes | set_brew_prefix | Get brew --prefix
  ansible.builtin.command: brew --prefix
  register: fish_get_brew_prefix
  changed_when: false
  check_mode: false

- name: includes | set_brew_prefix | Set Homebrew/Linuxbrew prefix
  ansible.builtin.set_fact:
    fish_brew_prefix: '{{ fish_get_brew_prefix.stdout }}'
